### ISSUE TITLE
Unexpected Exit Code -6 (Restart with :YcmRestartServer)

### ISSUE THREAD

**Issue by RameshSippy** [amix/vimrc#378]
I have almost managed to install YCM, however whenever I open mvim, I get the following error message:

`The Ycmd Server shutdown (restart with :YcmRestartServer).  Unexpected exit code -6`.

I looked online, but nowhere could I find what exit code `-6` represented!  The output of my log files is as follows:

```
2017-12-23 21:25:50,550 - ERROR - Unable to connect to server
Traceback (most recent call last):
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 217, in HandleServerException
    yield
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 237, in CheckIfServerIsReady
    'ready' )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 68, in GetDataFromHandler
    timeout ) )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 183, in JsonFromFuture
    response = future.result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=54499): Max retries exceeded with url: /ready (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10b7cbd50>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-23 21:25:50,655 - ERROR - The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code -6. Type ':YcmToggleLogs ycmd_54499_stderr_MqYNI6.log' to check the logs.
2017-12-23 21:26:05,494 - ERROR - Unable to connect to server
Traceback (most recent call last):
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 217, in HandleServerException
    yield
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/shutdown_request.py", line 37, in Start
    self.PostDataToHandler( {}, 'shutdown', TIMEOUT_SECONDS )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 78, in PostDataToHandler
    timeout ) )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 183, in JsonFromFuture
    response = future.result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=54499): Max retries exceeded with url: /shutdown (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10b80d2d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-23 21:26:05,618 - ERROR - Unable to connect to server
Traceback (most recent call last):
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 217, in HandleServerException
    yield
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 237, in CheckIfServerIsReady
    'ready' )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 68, in GetDataFromHandler
    timeout ) )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 183, in JsonFromFuture
    response = future.result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=54502): Max retries exceeded with url: /ready (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10b80d650>: Failed to establish a new connection: [Errno 61] Connection refused',))
2017-12-23 21:26:05,721 - ERROR - The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code -6. Type ':YcmToggleLogs ycmd_54502_stderr_fNX8sk.log' to check the logs.
2017-12-23 21:26:14,523 - ERROR - Unable to connect to server
Traceback (most recent call last):
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 217, in HandleServerException
    yield
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/debug_info_request.py", line 41, in Start
    self._response = self.PostDataToHandler( request_data, 'debug_info' )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 78, in PostDataToHandler
    timeout ) )
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 183, in JsonFromFuture
    response = future.result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/Users/abhisheknaik/.vim/bundle/YouCompleteMe/third_party/pythonfutures/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=54502): Max retries exceeded with url: /debug_info (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10b80da10>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

Note that I am trying to do all this on MacOS High Sierra.

**Comment by HUST-Jim** [comment]
I am having the same issue.

**Comment by amix** [comment]
Please report this to YouCompleteMe

**Comment by kirykr** [comment]
Just run: `python3 install.py --clang-completer --js-completer` inside `~/.vim/bundle/youcompleteme`
in `~/.vimrc` change the python_interpreter to `let g:ycm_path_to_python_interpreter = 'python3'
`

**Comment by robax** [comment]
A big thank you to @kirykr

**Comment by kirykr** [comment]
@robax. You are welcome.
