### ISSUE TITLE
powerline not found

### ISSUE THREAD

**Issue by marafa** [amix/vimrc#479]
fedora 29 upgraded from 28

powerline-fonts-2.7-1.fc29.noarch
vim-powerline-2.7-1.fc29.noarch
powerline-2.7-1.fc29.x86_64

i always get this error message when i run vi or vim

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'powerline'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'powerline'
An error occurred while importing powerline module.
This could be caused by invalid sys.path setting,
or by an incompatible Python version (powerline requires
Python 2.6, 2.7 or 3.2 and later to work). Please consult
the troubleshooting section in the documentation for
possible solutions.
Unable to import powerline, is it installed?
Press ENTER or type command to continue
```

things seem to be working tho but very irritating. 

also have tried
PYTHONPATH=/usr/lib/python3.7/site-packages/
then running vi .. same thing

**Comment by marafa** [comment]
duh! .. i was in a pipenv shell
