### ISSUE TITLE
python update_plugins.py issue

### ISSUE THREAD

**Issue by henosch** [amix/vimrc#559]
Traceback (most recent call last):
  File "update_plugins.py", line 107, in <module>
    [update(x) for x in PLUGINS.splitlines()]
  File "update_plugins.py", line 96, in update
    download_extract_replace(name, zip_path, temp_directory, SOURCE_DIR)
  File "update_plugins.py", line 89, in download_extract_replace
    shutil.move(plugin_temp_path, plugin_dest_path)
  File "/usr/lib/python2.7/shutil.py", line 325, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 153, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/tmpjrdTec/gist-vim-master'

**Comment by maikka39** [comment]
I've got the same bug

**Comment by amix** [comment]
This is already fixed. But thanks for reporting!
