### ISSUE TITLE
Updating does not work

### ISSUE THREAD

**Issue by fazlearefin** [amix/vimrc#615]
The existing instructions on updating vimrc does not work:

```
✔  ~
17:20 $ cd ~/.vim_runtime
✔  ~/.vim_runtime [master {origin/master}|✔ ]
17:20 $ git pull --rebase
Already up to date.
✔  ~/.vim_runtime [master {origin/master}|✔ ]
17:21 $ python update_plugins.py
Updated bufexplorer
Updated open_file_under_cursor.vim
Updated ctrlp.vim
Updated mayansmoke
Updated vim-indent-object
Updated vim-bundle-mako
Updated auto-pairs
Updated vim-colors-solarized
Updated ack.vim
Updated vim-yankstack
Updated nginx.vim
Updated tlib
Updated vim-addon-mw-utils
Updated nerdtree
Updated ale
Updated vim-less
Updated vim-pyte
Updated vim-snipmate
Updated vim-coffee-script
Updated vim-multiple-cursors
Updated gruvbox
Updated vim-flake8
Updated vim-pug
Updated lightline-ale
Updated vim-commentary
Updated vim-surround
Updated vim-expand-region
Updated vim-gist
Updated typescript-vim
Updated vim-python-pep8-indent
Updated lightline.vim
Updated rust.vim
Updated vim-abolish
Updated vim-markdown
Updated vim-javascript
Updated vim-ruby
Updated goyo.vim
Updated vim-repeat
Updated vim-zenroom2
Updated vim-fugitive
Updated vim-snippets
Updated vim-gitgutter
✔  ~/.vim_runtime [master {origin/master}|✚ 12…5]
17:21 $
```
Now, trying to update at a later time 
```
✔  ~
17:23 $ cd ~/.vim_runtime
✔  ~/.vim_runtime [master {origin/master}|✚ 12…5]
17:23 $ git pull --rebase
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
✘-128 ~/.vim_runtime [master {origin/master}|✚ 12…5]
17:23 $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   sources_non_forked/ale/ale_linters/ruby/sorbet.vim
        modified:   sources_non_forked/ale/doc/ale-ruby.txt
        modified:   sources_non_forked/nerdtree/CHANGELOG.md
        modified:   sources_non_forked/nerdtree/README.markdown
        modified:   sources_non_forked/typescript-vim/README.md
        modified:   sources_non_forked/vim-coffee-script/ftdetect/coffee.vim
        modified:   sources_non_forked/vim-fugitive/autoload/fugitive.vim
        modified:   sources_non_forked/vim-fugitive/doc/fugitive.txt
        modified:   sources_non_forked/vim-gitgutter/autoload/gitgutter/utility.vim
        modified:   sources_non_forked/vim-multiple-cursors/Gemfile.lock
        deleted:    sources_non_forked/vim-snipmate/doc/snipMate.txt
        modified:   sources_non_forked/vim-snippets/snippets/c.snippets

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sources_non_forked/typescript-vim/compiler/typescriptreact.vim
        sources_non_forked/typescript-vim/ftplugin/typescriptreact.vim
        sources_non_forked/typescript-vim/indent/typescriptreact.vim
        sources_non_forked/typescript-vim/syntax/typescriptreact.vim
        sources_non_forked/vim-snipmate/doc/SnipMate.txt

no changes added to commit (use "git add" and/or "git commit -a")
✔  ~/.vim_runtime [master {origin/master}|✚ 12…5]
17:23 $
```

I have [raised a PR](https://github.com/amix/vimrc/pull/614) to fix this.

**Comment by webcaptcha** [comment]
same for me, I don't know why that bunch of files has been modified

**Comment by fazlearefin** [comment]
> same for me, I don't know why that bunch of files has been modified

This command `python update_plugins.py` modifies the files.

**Comment by webcaptcha** [comment]
yeah, but why? I've perform such test as remove vim_runtime completely, then checkout new instance, then on NEW instance just do git pull, so no new commits obviously, and then python update plugins and got those updated files.

I'm finding that behavior odd

**Comment by fazlearefin** [comment]
This repo comes with its own set of files in the `sources_non_forked` directory. The `update_plugins.py` updates these files independently and hence we see these newer/changed files in the `.vim_runtime` directory.

This is a flaw in the design of this git repo. The `sources_non_forked` dir should be added to the .gitignore` file and the plugins should should not be maintained in this git repo, but downloaded separately during the installation process.

**Comment by sebelsc** [comment]
I have another issue while updating. When calling the `update_plugins.py` script, it always fails with:
```
Traceback (most recent call last):
  File "/Users/basti/.vim_runtime/update_plugins.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
I tried this with Python 2.7.17 and Python 3.9.1.

**Comment by bostonaholic** [comment]
> I have another issue while updating. When calling the `update_plugins.py` script, it always fails with:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/basti/.vim_runtime/update_plugins.py", line 12, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'
> ```
> 
> I tried this with Python 2.7.17 and Python 3.9.1.

@sebelsc I have an open PR that should address this: #595. If that works for you, it would be nice to have more comments and 👍  on that PR so the maintainers can merge it.

**Comment by amix** [comment]
Should be fixed. Thanks folks 🙏
